### ISSUE TITLE
Issues with resources in vendor/plugin directories

### ISSUE THREAD

**Issue by shanavas786** [asok/projectile-rails#114]
Though `projectile-rails-find-*` includes resources from plugin directories (`vendor/plugins`), it fails to visit the file from completion buffer as the filepath is wrong `app/resourcetype/name` instead of `vendor/plugins/plugin_name/app/resourcetype/name`.

A possible solution would be to list plugin resources as `plugin_name/controller_name` and use a function to resolve the filepath

**Comment by asok** [comment]
Could you provide a repository with such file structure, please?

**Comment by shanavas786** [comment]
See [Fedena](https://github.com/foradian/fedena/tree/master/vendor/plugins/fckeditor)
That happens whenever you create a rails plugin having controllers, models or other resources.

**Comment by asok** [comment]
I think I'm getting something wrong - I've clone this repository, set the `projectile-rails-root-file` to "Rakefile". Now when I run `projectile-rails-find-controller` I should be able to see "fckedit" controller in the completion but I don't see it.

**Comment by shanavas786** [comment]
After some debugging, I could see `projectile-rails-dir-files` sometimes includes some `vendor/plugins` directories. It happens in my project and not in Fedena.

Let me dig in more :smile:

**Comment by asok** [comment]
@shanavas786 if you have `projectile-enable-caching` set to `t` than projectile-rails is using the cache. Which gets rebuild from time to time (honestly I don't know of what basis cache refreshing occurs). So if you switch git branches and your cache is old it might not work correctly.
Run `projectile-invalidate-cache` in such scenarios.

I'll close this issue since it's quite old and reported only by one person.
