### ISSUE TITLE
Sidekiq directory

### ISSUE THREAD

**Issue by djolereject** [asok/projectile-rails#163]
Hi and thanks for the great lib. I'm facing a minor issue and I was wondering if it's something that is maybe resolved and I can't find it or might need resolving. 
Sidekiq is by default creating jobs in its own dir `/app/sidekiq` and I was wondrering if there might be a way of adding that path to `app/jobs` or even replacing it? I'm sure lot of Sidekiq users are facing this same problem where shortcut for jobs is just not useful and Sidekiq is arguably most popular Rails library for this so I guess it must not be that exotic of a problem.
What would be the solution for this?
Thanks

**Comment by asok** [comment]
Hi, what do you mean that Sidekiq creates jobs under `app/sidekiq`? Do you use some rake task to create new jobs?
I'm wondering whether that's an issue with your particular repository. Because AFAIK Sidekiq integrates nicely with ActiveJob and I would expect the jobs to be created under rails default `app/jobs`.

**Comment by djolereject** [comment]
Now I'm confused because it might be the case just for my setup, but I'm not sure what am I doing wrong here.
